### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by Aggror**
Fixed some spelling and typos based on feedback.

### CODE REVIEW

**Comment by xen2** [comment]
@Aggror I can't merge because you used @AggrorTest (either email or ssh key?) and CLA is not signed for this account.

**Comment by xen2** [comment]
@Aggror Also I renamed a bunch of files (since it matters for URL, so kept it consistent).
I recommend you to merge latest `master-3.1` (or restart from there).

**Comment by Aggror** [comment]
I restarted from 3.1. Hadn't set an upstream to  xenko-docs yet. I will do a fresh pull request. Not sure what that AggrorTest is.

**Comment by xen2** [comment]
Sorry, I should have told you earlier I rebased/squashed commits (had to do so because there was some unwanted files like .vs/ database, and git always forcing checkout of all files in history forever, I am careful to make sure no binary files get included by mistake).

**Pull request closed without merging**
